### ISSUE TITLE
Error loading Overlay css

### ISSUE THREAD

**Issue by Bonitis** [react-toolbox/react-toolbox#1039]
I am trying to include a Drawer component in my web app, which already uses sass and is configured with webpack to use sass-loader, and I keep getting this error:

```
C:\...\node_modules\react-toolbox\lib\overlay\theme.css:1
(function (exports, require, module, __filename, __dirname) { :root {
                                                              ^
SyntaxError: Unexpected token :
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:513:28)
    at Module._extensions..js (module.js:550:10)
    at Object.require.extensions.(anonymous function) [as .js] (C:\...\node_modules\babel-register\lib\node.js:152:7)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\...\node_modules\react-toolbox\lib\overlay\index.js:14:14)
```

Here is my code:

``` javascript
import { Drawer } from 'react-toolbox/lib/drawer';

...

return (
          <Drawer
            active={settingsActive}
            onOverlayClick={this.toggleSettings.bind(this)}
            type="left"
            className="content"
          >
            <div>page content</div>
          </Drawer>
        );
```

And my webpack loaders:
``` javascript
module: {
    loaders: [
      {
        test: /\.scss$/,
        loaders: ['style-loader', 'css-loader', 'sass-loader'],
      }, {
        test: /\.css$/,
        include: /node_modules/,
        loaders: ['style-loader', 'css-loader'],
      }, {
        test: /\.jsx*$/,
        exclude: [/node_modules/, /.+\.config.js/],
        loader: 'babel-loader',
      }, {
        test: /\.(jpe?g|gif|png|svg)$/i,
        loader: 'url-loader?limit=10000',
      }, {
        test: /\.json$/,
        loader: 'json-loader',
      },
      {test: /\.woff(\?v=\d+\.\d+\.\d+)?$/, loader: "file-loader?mimetype=application/font-woff"},
      {test: /\.woff2(\?v=\d+\.\d+\.\d+)?$/, loader: "file-loader?mimetype=application/font-woff"},
      {test: /\.ttf(\?v=\d+\.\d+\.\d+)?$/, loader: "file-loader?mimetype=application/octet-stream"},
      {test: /\.eot(\?v=\d+\.\d+\.\d+)?$/, loader: "file-loader"}
    ],
  },
```

If I try to load the component directly with no styles, like
``` javascript
import { Drawer } from 'react-toolbox/lib/drawer/Drawer';
```

I get the following error in the browser when I trigger the drawer opening:
`Uncaught TypeError: Cannot read property 'drawer' of undefined`

on this line
``` javascript
var _className = (0, _classnames3.default)([theme.drawer, theme[type]], _defineProperty({}, theme.active, active), className);
```

Any ideas about what I'm doing wrong?

**Comment by panvourtsis** [comment]
same here !

**Comment by javivelasco** [comment]
It looks like you are either trying out the beta version of `css-next` branch. It works with postcss instead of sass so you need to configure the pipeline to transform styles using CSS next. Actually the only thing you need is poscss-properties. You can also check github.com/react-toolbox/react-toolbox-themr to skip the setup!
