### ISSUE TITLE
Webpack 2 configuration?

### ISSUE THREAD

**Issue by Cleanshooter** [react-toolbox/react-toolbox#1299]
I'm working with the layout tutorial here: http://react-toolbox.com/#/components/layout

 and when following the instructions and modding it to suit my needs I end up with the following code.

```
import React, { PropTypes } from 'react';
import Message from '../containers/Message';

//React-Toolbox implementation
import { ThemeProvider } from 'react-css-themr';
import theme from '../css/react-toolbox/theme';
import { AppBar } from 'react-toolbox/lib/app_bar';
import { Layout, NavDrawer, Panel, Sidebar } from 'react-toolbox';
import AppBarTheme from '../css/react-toolbox/appBar.css'

const App = ({children}) => {
  return (
    <ThemeProvider theme={theme}>
	    <div>
	    	<AppBar title='Test' theme={AppBarTheme}>
			  </AppBar>
			  <Layout>
	          <NavDrawer>
	              <p>
	                  Navigation, account switcher, etc. go here.
	              </p>
	          </NavDrawer>
	          <Panel>
	              <Message />
	  						{children}
	          </Panel>
	          <Sidebar pinned={ false } width={ 2 }>
	              <div style={{ flex: 1 }}>
	                  <p>Supplemental content goes here.</p>
	              </div>
	          </Sidebar>
	      </Layout>
	    </div>
    </ThemeProvider>
  );
};

export default App;
```

When I compile it this is the error I get:

```
/Project/node_modules/react-toolbox/lib/ripple/theme.css:1
(function (exports, require, module, __filename, __dirname) { :root {
                                                              ^
SyntaxError: Unexpected token :
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Project/node_modules/react-toolbox/lib/ripple/index.js:13:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Project/node_modules/react-toolbox/lib/button/index.js:20:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Project/node_modules/react-toolbox/lib/app_bar/index.js:14:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
```

**Comment by Cleanshooter** [comment]
y best guess at this point is that the `import { Layout, NavDrawer, Panel, Sidebar } from 'react-toolbox';` is the culprit.  I think that by referencing the base project 'react-toolbox' instead of isolating each component like 'react-toolbox/lib/layout' the entire thing is attempting to compile.  I can't understand why it would compile though... I should post my webpack config....

**Comment by Cleanshooter** [comment]
dev Browser config:

```
{
    devtool: 'eval',
    context: PATHS.app,
    entry: { app: ['./client', hotMiddlewareScript] },
    node,
    output: {
      path: PATHS.assets,
      filename: '[name].js',
      publicPath: PATHS.public
    },
    module: { rules: rules({ production: false, browser: true }) },
    resolve,
    plugins: plugins({ production: false, browser: true })
  };
```

const path = require('path');
const ExtractTextPlugin = require('extract-text-webpack-plugin');
const postcssImport = require('postcss-import');
const postcssCssnext = require('postcss-cssnext');
const postcssReporter = require('postcss-reporter');
const PATHS = require('../paths');

CSS Rules:

```
module.exports = ({ production = false, browser = false } = {}) => {
  /*
   * modules: boolean - Enable/Disable CSS Modules
   * importLoaders: number - Number of loaders applied before CSS loader
   *
   * Read more about css-loader options
   * https://webpack.js.org/loaders/css-loader/#options
   *
   * For server-side rendering we use css-loader/locals as we do not want to
   * embed CSS. However, we still require the mappings to insert as className in
   * our views.
   *
   * Referenced from: https://github.com/webpack-contrib/css-loader#css-scope
   *
   * For prerendering with extract-text-webpack-plugin you should use
   * css-loader/locals instead of style-loader!css-loader in the prerendering bundle.
   * It doesn't embed CSS but only exports the identifier mappings.
   */
  const localIndentName = 'localIdentName=[name]__[local]___[hash:base64:5]';

  const createCssLoaders = embedCssInBundle => ([
    {
      loader: embedCssInBundle ? 'css-loader' : 'css-loader/locals',
      options: {
        localIndentName,
        sourceMap: true,
        modules: true,
        importLoaders: 1
      }
    },
    {
      loader: 'postcss-loader',
      options: {
        plugins: [
          postcssImport({ path: path.resolve(PATHS.app, './css') }),
          postcssCssnext({ browsers: ['> 1%', 'last 2 versions'] }),
          postcssReporter({ clearMessages: true })
        ]
      }
    }
  ]);

  const createBrowserLoaders = extractCssToFile => loaders => {
    if (extractCssToFile) {
      return ExtractTextPlugin.extract({
        fallback: 'style-loader',
        use: loaders
      });
    }
    return [{ loader: 'style-loader' }, ...loaders];
  };

  const serverLoaders = createCssLoaders(false);
  const browserLoaders = createBrowserLoaders(production)(createCssLoaders(true));

  return {
    test: /\.css$/,
    use: browser ? browserLoaders : serverLoaders
  };
};
```

using this project as a boilerplate: https://github.com/reactGo/reactGo

**Comment by Cleanshooter** [comment]
So after some experimentation it seems it's the webpack configuration... my project is using webpack 2 and the instructions are for webpack 1... 

curent error:

```
ERROR in ../~/react-toolbox/lib/app_bar/theme.css
Module build failed: Unknown word (5:1)

  3 | // load the styles
  4 | var content = require("!!../../../css-loader/index.js?sourceMap&modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!postcss?sourceMap&sourceComments!../../../postcss-loader/index.js??ref--3-2!./theme.css");
> 5 | if(typeof content === 'string') content = [[module.id, content, '']];
    | ^
  6 | // add the styles to the DOM
  7 | var update = require("!../../../style-loader/addStyles.js")(content, {});

Syntax Error: Unknown word (5:1)

  3 | // load the styles
  4 | var content = require("!!../../../css-loader/index.js?sourceMap&modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!postcss?sourceMap&sourceComments!../../../postcss-loader/index.js??ref--3-2!./theme.css");
> 5 | if(typeof content === 'string') content = [[module.id, content, '']];
    | ^
  6 | // add the styles to the DOM
  7 | var update = require("!../../../style-loader/addStyles.js")(content, {});

    at /Project/node_modules/postcss-loader/index.js:146:22
    at process._tickCallback (internal/process/next_tick.js:103:7)
 @ ../~/react-toolbox/lib/app_bar/index.js 16:13-35
 @ ./containers/App.jsx
 @ ./pages/App.jsx
 @ ./pages/index.js
 @ ./routes.jsx
 @ ../server/render/middleware.js
 @ ../server/index.js
```

**Does anyone know what the config should like for using Webpack 2 with React-Toolbox?**

**Comment by Cleanshooter** [comment]
Found this in the react-toolbox example webpack config

```
{
    	test: /\.css$/,
    	include: [PATHS.modules + '/react-toolbox/', PATHS.modules + '/react-css-themr/'],
    	use: [
        "style-loader",
        {
          loader: "css-loader",
          options: {
            modules: true,
            sourceMap: true,
            importLoaders: 1,
            localIdentName: "[name]--[local]--[hash:base64:8]"
          }
        },
        "postcss-loader" // has separate config, see postcss.config.js nearby
      ]
    },
```

It took care of the previous issue but I'm still not able to successfully build my app.

It dies while building the dev server:

```
/Project/compiled/webpack:/~/style-loader/addStyles.js:31
	if (typeof options.singleton === "undefined") options.singleton = isOldIE();
^
ReferenceError: self is not defined
    at /Project/compiled/webpack:/~/style-loader/addStyles.js:14:1
    at /Project/compiled/webpack:/~/style-loader/addStyles.js:9:1
    at module.exports.module.exports (/Project/compiled/webpack:/~/style-loader/addStyles.js:31:1)
    at Object.module.exports.module.exports (/Project/compiled/webpack:/~/react-toolbox/lib/ripple/theme.css?377c:7:1)
    at __webpack_require__ (/Project/compiled/webpack:/webpack/bootstrap 4656726d38ca2e29f112:19:1)
    at Object.module.exports.Object.defineProperty.value (/Project/compiled/webpack:/~/react-toolbox/lib/ripple/index.js:13:1)
    at __webpack_require__ (/Project/compiled/webpack:/webpack/bootstrap 4656726d38ca2e29f112:19:1)
    at Object.module.exports.Object.defineProperty.value (/Project/compiled/webpack:/~/react-toolbox/lib/button/index.js:20:1)
    at __webpack_require__ (/Project/compiled/webpack:/webpack/bootstrap 4656726d38ca2e29f112:19:1)
    at Object.module.exports.Object.defineProperty.value (/Project/compiled/webpack:/~/react-toolbox/lib/app_bar/index.js:14:1)
    at __webpack_require__ (/Project/compiled/webpack:/webpack/bootstrap 4656726d38ca2e29f112:19:1)
    at Object.module.exports.Object.defineProperty.value (/Project/compiled/webpack:/containers/App.jsx:10:1)
    at __webpack_require__ (/Project/compiled/webpack:/webpack/bootstrap 4656726d38ca2e29f112:19:1)
    at Object.module.exports.Object.defineProperty.value (/Project/compiled/webpack:/pages/App.jsx:3:1)
    at __webpack_require__ (/Project/compiled/webpack:/webpack/bootstrap 4656726d38ca2e29f112:19:1)
    at Object.module.exports.Object.defineProperty.value (/Project/compiled/server.dev.js:12738:12)
    at __webpack_require__ (/Project/compiled/webpack:/webpack/bootstrap 4656726d38ca2e29f112:19:1)
    at Object.module.exports.Object.defineProperty.value (/Project/compiled/webpack:/routes.jsx:4:1)
    at __webpack_require__ (/Project/compiled/webpack:/webpack/bootstrap 4656726d38ca2e29f112:19:1)
    at Object.<anonymous> (/Project/compiled/webpack:/server/render/middleware.js:3:1)
    at __webpack_require__ (/Project/compiled/webpack:/webpack/bootstrap 4656726d38ca2e29f112:19:1)
    at Object.<anonymous> (/Project/compiled/webpack:/server/index.js:9:1)
    at __webpack_require__ (/Project/compiled/webpack:/webpack/bootstrap 4656726d38ca2e29f112:19:1)
    at module.exports.validateFormat (/Project/compiled/webpack:/webpack/bootstrap 4656726d38ca2e29f112:65:1)
    at Object.<anonymous> (/Project/compiled/server.dev.js:71:10)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)

```

**Comment by Cleanshooter** [comment]
So after digging deeper into the issues posted here it seems my issues has to do with Server Side Rendering.  I'm checking this repo now to see if it can help me find an answer...

https://github.com/romppra/react-toolbox-ssr-testbench

**Comment by bassbump** [comment]
Same exact issue here

**Comment by Cleanshooter** [comment]
After what seems like endless digging I found  solution.  The Example on the demo site used this:

`import { Layout, NavDrawer, Panel, Sidebar } from 'react-toolbox';`

It should be:

`import { Layout, NavDrawer, Panel, Sidebar } from 'react-toolbox**/lib/layout**';`

For some reason when you try and import from the base of this component it goes nuts...

also if your using ReatGo like me make your return function look as follows in your webpack/rules/css.js:

```
  return {
    test: /\.css$/,
    use: browser ? browserLoaders : serverLoaders,
    include: [PATHS.app, PATHS.modules + '/react-toolbox/']
  };
```

**Comment by javivelasco** [comment]
Here you have a [working example](https://github.com/react-toolbox/react-toolbox-example) with Webpack 2!

**Comment by adamhenson** [comment]
I too struggled in configuring a universal app with Webpack 2, React Toolbox, React Router, etc. Eventually, I was able to come up with a working example. Hope it helps others who've encountered the same struggle. I forked and created a React Toolbox feature branch from [richardkall/react-starter](https://github.com/richardkall/react-starter) to demonstrate a simple universal app It does rely on [css-modules-require-hook](https://github.com/css-modules/css-modules-require-hook).

**Comment by creeperyang** [comment]
For those who don't want to use `css-modules-require-hook`, [`iso-morphic-style-loader`](https://github.com/creeperyang/iso-morphic-style-loader) is an alternative.

- If you don't care about ssr, just config the loader as `style-loader`. It will eliminate all errors that `style-loader` will throw and process styles correctly in browser.
- If you prefer ssr, just follow the doc, it's easy.


```js
{
        test: /\.css$/,
        rules: [
          // Handle react-toolbox style since it cannot intergrate with isomorphic-style-loader well.
          {
            issuer: path.resolve(__dirname, '../node_modules/react-toolbox'),
            use: 'iso-morphic-style-loader'
          },
}
```
