### ISSUE TITLE
unexpected token when integrating button to storybook

### ISSUE THREAD

**Issue by kuka-radovan** [react-toolbox/react-toolbox#1430]
Hi, I have a problem of creating a simple react-toolbox button story in a storybook. I want to highlight that, all my setup of react-toolbox in application itself works well. But when I copied and slightly edited the appropriate webpack.config.js projects to the .storybook directory that looks like this:

```
module.exports = {
  module: {
    rules: [
      {
        test: /\.css$/,
        use: [
          'style-loader',
          {
            loader: 'css-loader',
            options: {
              modules: true,
              importLoaders: 1,
              sourceMap: true,
              localIdentName: '[name]--[local]--[hash:base64:8]',
            },
          },
          {
            loader: 'postcss-loader',
            options: {
              plugins: function() {
                return [
                  require('postcss-import'),
                  require('postcss-mixins'),
                  require('postcss-each'),
                  require('postcss-cssnext')
                ]
              }
            },
          },
        ],
      }
    ]
  }
}
```

I got this error and I'm not sure which loader I'm missing in my config.

```
ERROR in ./~/react-toolbox/lib/button/theme.css
Module parse failed: /Users/kuko/Workspace/in2core/qtakecloud-frontend/node_modules/react-toolbox/lib/button/theme.css Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (1:0)
    at Parser.pp$4.raise (/Users/kuko/Workspace/in2core/qtakecloud-frontend/node_modules/@kadira/storybook/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp.unexpected (/Users/kuko/Workspace/in2core/qtakecloud-frontend/node_modules/@kadira/storybook/node_modules/acorn/dist/acorn.js:603:10)
    at Parser.pp$3.parseExprAtom (/Users/kuko/Workspace/in2core/qtakecloud-frontend/node_modules/@kadira/storybook/node_modules/acorn/dist/acorn.js:1822:12)
    at Parser.pp$3.parseExprSubscripts (/Users/kuko/Workspace/in2core/qtakecloud-frontend/node_modules/@kadira/storybook/node_modules/acorn/dist/acorn.js:1715:21)
    at Parser.pp$3.parseMaybeUnary (/Users/kuko/Workspace/in2core/qtakecloud-frontend/node_modules/@kadira/storybook/node_modules/acorn/dist/acorn.js:1692:19)
    at Parser.pp$3.parseExprOps (/Users/kuko/Workspace/in2core/qtakecloud-frontend/node_modules/@kadira/storybook/node_modules/acorn/dist/acorn.js:1637:21)
    at Parser.pp$3.parseMaybeConditional (/Users/kuko/Workspace/in2core/qtakecloud-frontend/node_modules/@kadira/storybook/node_modules/acorn/dist/acorn.js:1620:21)
    at Parser.pp$3.parseMaybeAssign (/Users/kuko/Workspace/in2core/qtakecloud-frontend/node_modules/@kadira/storybook/node_modules/acorn/dist/acorn.js:1597:21)
    at Parser.pp$3.parseExpression (/Users/kuko/Workspace/in2core/qtakecloud-frontend/node_modules/@kadira/storybook/node_modules/acorn/dist/acorn.js:1573:21)
    at Parser.pp$1.parseStatement (/Users/kuko/Workspace/in2core/qtakecloud-frontend/node_modules/@kadira/storybook/node_modules/acorn/dist/acorn.js:727:47)
 @ ./~/react-toolbox/lib/button/index.js 24:13-35
ERROR in ./~/react-toolbox/lib/ripple/theme.css
Module parse failed: /Users/kuko/Workspace/in2core/qtakecloud-frontend/node_modules/react-toolbox/lib/ripple/theme.css Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (1:0)
    at Parser.pp$4.raise (/Users/kuko/Workspace/in2core/qtakecloud-frontend/node_modules/@kadira/storybook/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp.unexpected (/Users/kuko/Workspace/in2core/qtakecloud-frontend/node_modules/@kadira/storybook/node_modules/acorn/dist/acorn.js:603:10)
    at Parser.pp$3.parseExprAtom (/Users/kuko/Workspace/in2core/qtakecloud-frontend/node_modules/@kadira/storybook/node_modules/acorn/dist/acorn.js:1822:12)
    at Parser.pp$3.parseExprSubscripts (/Users/kuko/Workspace/in2core/qtakecloud-frontend/node_modules/@kadira/storybook/node_modules/acorn/dist/acorn.js:1715:21)
    at Parser.pp$3.parseMaybeUnary (/Users/kuko/Workspace/in2core/qtakecloud-frontend/node_modules/@kadira/storybook/node_modules/acorn/dist/acorn.js:1692:19)
    at Parser.pp$3.parseExprOps (/Users/kuko/Workspace/in2core/qtakecloud-frontend/node_modules/@kadira/storybook/node_modules/acorn/dist/acorn.js:1637:21)
    at Parser.pp$3.parseMaybeConditional (/Users/kuko/Workspace/in2core/qtakecloud-frontend/node_modules/@kadira/storybook/node_modules/acorn/dist/acorn.js:1620:21)
    at Parser.pp$3.parseMaybeAssign (/Users/kuko/Workspace/in2core/qtakecloud-frontend/node_modules/@kadira/storybook/node_modules/acorn/dist/acorn.js:1597:21)
    at Parser.pp$3.parseExpression (/Users/kuko/Workspace/in2core/qtakecloud-frontend/node_modules/@kadira/storybook/node_modules/acorn/dist/acorn.js:1573:21)
    at Parser.pp$1.parseStatement (/Users/kuko/Workspace/in2core/qtakecloud-frontend/node_modules/@kadira/storybook/node_modules/acorn/dist/acorn.js:727:47)
 @ ./~/react-toolbox/lib/ripple/index.js 13:13-35
```

It looks like there is a problem with `@import` but why everything works correctly in my app? Is here anybody, that can help me to solve this issue?
Thanks for any advice.

**Comment by brian-gates** [comment]
I'm running into this issue as well.  Any insight would be appreciated.

**Comment by kuka-radovan** [comment]
It is working now. I haven't done any changes, I just updated packages, so probably some of them had a bug that was fixed.

**Comment by kuka-radovan** [comment]
@brian-gates Have you solved that issue somehow? I tried few configurations without effect and I have no more ideas.

**Comment by zan-rosenthal** [comment]
@kuka-radovan @brian-gates I was running into this issue as well. I finally got it working. I've pasted my `.storybook/webpack.config.js` below. Storybook still uses Webpack 1, so I wasn't able to get it to work with Webpack 2 syntax. Hope it helps:

`/* eslint-env node */
const path = require('path')

module.exports = {
  resolve: {
    root: path.resolve(__dirname, '../'),
  },
  module: {
    loaders: [
      {
        test: /.scss$/,
        loader: 'style!css?modules!sass?modules',
      },
      {
        test: /\.css$/,
        exclude: path.resolve(path.resolve(__dirname, '../node_modules'), 'material-design-icons'),
        loader: 'style!css?sourceMap&modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!postcss'
      }
    ]
  },
  postcss: () => {
    return [
      require('postcss-cssnext')(),
    ]
  }
}`

**Comment by kuka-radovan** [comment]
@zan-rosenthal Thanks a lot. I didn't realize that.
