### ISSUE TITLE
react-toolbox-themr fails in beta-10

### ISSUE THREAD

**Issue by plougsgaard** [react-toolbox/react-toolbox#1494]
## Setup

- Upgraded from beta-8 to beta-10
- Running inside a create-react-app 1.0.6

## Error running themr

```
→ yarn run react-toolbox-themr
yarn run v0.24.5
$ react-toolbox-themr
Error: Expected pseudo-class or pseudo-element
    at new error (~/MyProject/node_modules/postcss-selector-parser/dist/processor.js:29:23)
    at Parser.error (~/MyProject/node_modules/postcss-selector-parser/dist/parser.js:234:15)
    at Parser.pseudo (~/MyProject/node_modules/postcss-selector-parser/dist/parser.js:336:25)
    at Parser.parse (~/MyProject/node_modules/postcss-selector-parser/dist/parser.js:551:22)
    at Parser.loop (~/MyProject/node_modules/postcss-selector-parser/dist/parser.js:519:18)
    at new Parser (~/MyProject/node_modules/postcss-selector-parser/dist/parser.js:104:21)
    at Processor.process (~/MyProject/node_modules/postcss-selector-parser/dist/processor.js:26:21)
    at ~/MyProject/node_modules/postcss-attribute-case-insensitive/dist/index.js:107:68
    at ~/MyProject/node_modules/postcss/lib/container.js:241:28
    at ~/MyProject/node_modules/postcss/lib/container.js:148:26
```

## Error building app

Additionally I also get an error building the project.

```
→ yarn build
[..]
./~/react-toolbox/lib/autocomplete/theme.css
Module build failed: Error: Unexpected "space" found.
```

Everything works with beta-8. I think it's caused by the `postcss` dependency upgrade.

**Comment by javivelasco** [comment]
Yes, I'm fixing it and releasing a new version, sorry!

**Comment by javivelasco** [comment]
Done, there was an small error, now it should work :)

**Comment by plougsgaard** [comment]
Beta-11 works like a charm! Thanks for fixing this!

**Comment by javivelasco** [comment]
Glad to know!! Thank you! :)
