### ISSUE TITLE
React-boilerplate + react-toolbox: Cannot resolve 'file' or 'directory' ./style

### ISSUE THREAD

**Issue by Natanael1234** [react-toolbox/react-toolbox#527]
I'm using [react-boilerplate](https://github.com/mxstbr/react-boilerplate) as base to my project, since it have support do Redux.

When I access my app I get the following error in the terminal:

```
ERROR in ./~/react-toolbox/lib/button/Button.js
Module not found: Error: Can't resolve './style' in 'E:\ReactLaravel\Boilerplate\react-boilerplate-master\node_modules\react-toolbox\lib\button'
 @ ./~/react-toolbox/lib/button/Button.js 28:13-31

ERROR in ./~/react-toolbox/lib/button/IconButton.js
Module not found: Error: Can't resolve './style' in 'E:\ReactLaravel\Boilerplate\react-boilerplate-master\node_modules\react-toolbox\lib\button'
 @ ./~/react-toolbox/lib/button/IconButton.js 28:13-31

ERROR in ./~/react-toolbox/lib/ripple/Ripple.js
Module not found: Error: Can't resolve './style' in 'E:\ReactLaravel\Boilerplate\react-boilerplate-master\node_modules\react-toolbox\lib\ripple'
 @ ./~/react-toolbox/lib/ripple/Ripple.js 23:13-31
Child html-webpack-plugin for "index.html":
         Asset     Size  Chunks       Chunk Names
    index.html  20.5 kB       0
    chunk    {0} index.html 1.03 kB [rendered]
        [0] ./~/html-webpack-plugin/lib/loader.js!./app/index.html 1.03 kB {0} [built]
Error: no such file or directory
    at MemoryFileSystem.readFileSync (E:\ReactLaravel\Boilerplate\react-boilerplate-master\node_modules\webpack-dev-middleware\node_modules\memory-fs\lib\MemoryFileSystem.js:107:10)
    at app.get (E:\ReactLaravel\Boilerplate\react-boilerplate-master\server\middlewares\frontendMiddleware.js:25:21)
    at Layer.handle [as handle_request] (E:\ReactLaravel\Boilerplate\react-boilerplate-master\node_modules\express\lib\router\layer.js:95:5)
    at next (E:\ReactLaravel\Boilerplate\react-boilerplate-master\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (E:\ReactLaravel\Boilerplate\react-boilerplate-master\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (E:\ReactLaravel\Boilerplate\react-boilerplate-master\node_modules\express\lib\router\layer.js:95:5)
    at E:\ReactLaravel\Boilerplate\react-boilerplate-master\node_modules\express\lib\router\index.js:277:22
    at param (E:\ReactLaravel\Boilerplate\react-boilerplate-master\node_modules\express\lib\router\index.js:349:14)
    at param (E:\ReactLaravel\Boilerplate\react-boilerplate-master\node_modules\express\lib\router\index.js:365:14)
    at Function.process_params (E:\ReactLaravel\Boilerplate\react-boilerplate-master\node_modules\express\lib\router\index.js:410:3)
    at next (E:\ReactLaravel\Boilerplate\react-boilerplate-master\node_modules\express\lib\router\index.js:271:10)
    at middleware (E:\ReactLaravel\Boilerplate\react-boilerplate-master\node_modules\webpack-hot-middleware\middleware.js:39:48)
    at Layer.handle [as handle_request] (E:\ReactLaravel\Boilerplate\react-boilerplate-master\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (E:\ReactLaravel\Boilerplate\react-boilerplate-master\node_modules\express\lib\router\index.js:312:13)
    at E:\ReactLaravel\Boilerplate\react-boilerplate-master\node_modules\express\lib\router\index.js:280:7
    at Function.process_params (E:\ReactLaravel\Boilerplate\react-boilerplate-master\node_modules\express\lib\router\index.js:330:12)



```

My App/containers/MyContainer/index.js which is the main entry for this part of the application:
[index.zip](https://github.com/react-toolbox/react-toolbox/files/285221/index.zip)

My package.json:
[package.json.zip](https://github.com/react-toolbox/react-toolbox/files/285226/package.json.zip)

The file I believe is the equivalent to webpack.config.js in this boilerplate template:
[webpack.test.babel.zip](https://github.com/react-toolbox/react-toolbox/files/285227/webpack.test.babel.zip)

**Comment by chpasha** [comment]
I have exactly same problem with same boilerplate

**Comment by Natanael1234** [comment]
I made this and not solved:

https://github.com/mxstbr/react-boilerplate/blob/master/docs/css/sass.md

**Comment by yongshin** [comment]
Same issue here

**Comment by javivelasco** [comment]
Try 1.0.0!

**Comment by DenisNeustroev** [comment]
lol, just add .scss extension to webpack.base.babel.js

![image](https://cloud.githubusercontent.com/assets/4533828/15805115/4c23a802-2b28-11e6-91cb-1800d967c576.png)

**Comment by jhardin293** [comment]
What is the status of this issue? I have the same problem and @DenisNeustroev solution, unfortunately didint work :(

**Comment by DenisNeustroev** [comment]
@jhardin293 try this:

webpack.base.babel.js
![image](https://cloud.githubusercontent.com/assets/4533828/16177484/aee4d5d2-3637-11e6-9a83-166aacf76950.png)
```
      // Transform react-toolbox styles with SASS
      test: /\.scss$/,
      include: /node_modules\/react-toolbox/,
      loader: options.sassLoaders,
```

webpack.dev.babel.js
![image](https://cloud.githubusercontent.com/assets/4533828/16177489/d5a66938-3637-11e6-8202-f8593bd3d46d.png)
```
  sassLoaders: 'style-loader!css-loader?localIdentName=[local]__[path][name]__[hash:base64:5]&modules&importLoaders=1&sourceMap!postcss-loader!sass-loader',
```

**Comment by javivelasco** [comment]
Although this is a common issue, it is *not* a project issue. The setup may not look issue but you just need a module bundler able to load SASS files. I'm closing this issue though, any of the solutions posted in this thread should work and, in other case, refer to the [react-toolbox-example])(github.com/react-toolbox/react-toolbox-example)
