### ISSUE TITLE
Babel not aware of (s)css syntax?

### ISSUE THREAD

**Issue by westhomas** [react-toolbox/react-toolbox#633]
I'm sure this is something simple. But I've followed the guides/issue comments trying to get toolbox to work in my isomorphic app. I've tried the css-modules-require-hook. I just keep getting this syntax error about the @ symbol.

Any thoughts? I feel like I'm missing something but I'm out of my depth here.

```
node server.js

project/node_modules/react-toolbox/lib/ripple/theme.scss:1
(function (exports, require, module, __filename, __dirname) { @import "../colors";
                                                              ^
SyntaxError: Unexpected token ILLEGAL
    at Object.exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:513:28)
    at Module._extensions..js (module.js:550:10)
    at Object.require.extensions.(anonymous function) [as .js] (project/node_modules/babel-register/lib/node.js:166:7)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (project/node_modules/react-toolbox/lib/ripple/index.js:13:14)
```

My webpack-dev-server runs on port 3001 for HMR and my express runs on 3000. Configs below.

webpack.config.js
```
var path = require('path');
var webpack = require('webpack');
var ExtractTextPlugin = require('extract-text-webpack-plugin');
var BUILD_DIR = path.resolve(__dirname, 'public');
var APP_DIR = path.resolve(__dirname, 'app');

var config = {
    devtool: "source-map",
    entry: [
        'webpack-dev-server/client?http://localhost:3001/', // WebpackDevServer host and port
        'webpack/hot/only-dev-server', // "only" prevents reload on syntax errors
        path.resolve(APP_DIR, 'main.js')
    ],
    output: {
        path: BUILD_DIR,
        publicPath: 'http://localhost:3001/js/',
        filename: '[name].js'
    },
    module: {
        loaders: [
            { 
                test: /\.jsx?$/,
                loaders: ['react-hot', 'jsx?harmony', 'babel?'+JSON.stringify({"presets": ['es2015', 'stage-0', 'react']})],
                exclude: /node_modules/,
                include: APP_DIR
            },
            {
                test: /\.scss$/,
                loaders: ["style", "css", "sass"]
            },
            {
                test: /\.css$/,
                loader: ExtractTextPlugin.extract('style', 'css?sourceMap&modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!postcss')
            }
        ]
    },
    postcss: [
        require('postcss-font-magician'),
        require('autoprefixer'),
    ],
    sassLoader: {
        data: '@import "theme/_config.scss";',
        includePaths: [path.resolve(__dirname, './app')]
    },    
    plugins: [
        new ExtractTextPlugin('main.css', { allChunks: true }),
        new webpack.optimize.OccurenceOrderPlugin(),
        new webpack.HotModuleReplacementPlugin(),
        new webpack.NoErrorsPlugin()
    ]
};
module.exports = config;
```

server.js
```
require('babel-register');

var express = require('express');
var path = require('path');
var logger = require('morgan');
var bodyParser = require('body-parser');

var swig  = require('swig');
var React = require('react');
var ReactDOM = require('react-dom/server');
var Router = require('react-router');


var routes = require('./app/routes');

var hook = require('css-modules-require-hook');
var sass = require('node-sass');

const nodeModules = path.resolve(__dirname, '../node_modules');

hook({
  extensions: ['.scss'],
  preprocessCss: (data, file) => sass.renderSync({file, data, includePaths: [nodeModules]}).css
});


var app = express();

app.set('port', process.env.PORT || 3000);
app.use(logger('dev'));
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: false }));

var webpack = require("webpack");
var webpackConfig = require('./webpack.config');
var compiler = webpack(webpackConfig);
app.use(require('webpack-hot-middleware')(compiler));

console.log('DEVOLOPMENT ENVIRONMENT: Turning on WebPack Middleware...');

var WebpackDevServer = require("webpack-dev-server");
var port = 3001;
var ip = '0.0.0.0';
var server = new WebpackDevServer(compiler, {
  contentBase: webpackConfig.output.path,
  hot: true,
  historyApiFallback: true,
  filename: path.resolve(webpackConfig.output.path, webpackConfig.output.filename),
  publicPath: webpackConfig.output.publicPath,
  headers: { "Access-Control-Allow-Origin": "*" },
  stats: { colors: true }
});
server.listen(port, ip, function(err) {
    if(err) {
        return console.log(err);
    }
    console.log('Listening at ' + ip + ':' + port);
});


//React routes middleware
app.use(function(req, res) {
  Router.match({ routes: routes.default, location: req.url }, function(err, redirectLocation, renderProps) {
    if (err) {
      res.status(500).send(err.message)
    } else if (redirectLocation) {
      res.status(302).redirect(redirectLocation.pathname + redirectLocation.search)
    } else if (renderProps) {
      var html = ReactDOM.renderToString(React.createElement(Router.RoutingContext, renderProps));
      var page = swig.renderFile('views/index.html', { html: html });
      res.status(200).send(page);
    } else {
      res.status(404).send('OH HAI. No page for that.')
    }
  });
});

//server.listen(app.get('port'), function() {
app.listen(app.get('port'), function() {
  console.log('Express server listening on port ' + app.get('port'));
});
```

**Comment by javivelasco** [comment]
It looks like the problem is happening with your paths. Babel is trying to parse files that has `.scss` extension. I'm not sure where the problem is in your config but it's definitively a config related issue so I'm going to close.

Please try the example. Make sure your CSS Modules hook is able to read and parse SCSS. It's not configured by default!

**Comment by jagged3dge** [comment]
I realise this is a config issue and this issue is closed. However, I'm in the same boat as @westhomas . It would be really appreciated if @westhomas can post any solution they come up with to resolve this problem. Thanks in advance!

**Comment by westhomas** [comment]
The lack of isomorphic support was a deal killer for me. I realize it's probably possible to get it working, but I simply lacked the time to figure it out. I gave up.

**Comment by jagged3dge** [comment]
Ah. Thanks for clarifying Wes. I found a dirty hack to suppress this issue. I came to know nodejs exposes a `require.extensions` API. Using this to suppress handling of scss is trivial.

Fair warning: THIS IS A DIRTY HACK (in my books atleast, can call it _unwieldy_ at best)

```js
require.extensions[ '.scss' ] = function() {
  return;
};
```
This prevents node/babel from handling style requires like `var style = require('./style.scss');`
Webpack will definitely parse these statements tho, so client-side builds should not be affected.

**Comment by jagged3dge** [comment]
There is a valid alternative, if you dont mind adding another dependency. Using `css-modules-require-hook` and `node-sass` directly, we can arrange for `.scss` files to be required properly while doing SSR.
```js
// DEPRECATED: Not required (pun intended) anymore! Workaround follows...
// require.extensions['.scss'] = function() {
//   return;
// };

import path from 'path';

require('css-modules-require-hook')({
  generateScopedName: '[name]__[local]-[hash:base64:5]',
  mode: 'local',
  rootDir: './app',
  extensions: [ '.scss', '.css' ],
  preprocessCss: (css, filepath) => {
    if (filepath.indexOf('.scss') > -1) {
      return sassCompiler.renderSync({
        data: css,
        file: filepath,
        includePaths: [
          path.resolve(__dirname, '../app'),
          path.resolve(__dirname, '../node_modules')
        ]
      }).css
    }

    return css;
  }
});
```

I hope this helps any future visitors to fix their SSR with React Toolbox.

**Comment by javivelasco** [comment]
That's exactly what I did to make it work in the past but don't worry, with PostCSS it's going to be easier in the next major release

**Comment by ngoctranfire** [comment]
I'm still getting this issue, and I've tried all the solutions above and the error still happens. Any clues? Did anyone fix it? I tried switching to webpack-isomorphic-tools and it didn't even work.
