### ISSUE TITLE
When I try to use datepicker I always have this error:Uncaught Error: Cannot find module "./slide-left.scss"

### ISSUE THREAD

**Issue by dvdgarcia** [react-toolbox/react-toolbox#645]
When I try to use datepicker I always have this error,
Uncaught Error: Cannot find module "./slide-left.scss"
 I have installed webpack and sass:

any idea?

**Comment by dvdgarcia** [comment]
when I see the console, bundle is failing:


ERROR in ./~/react-toolbox/lib/date_picker/theme.scss
Module parse failed: /Users/david/projects/pexwidgets/node_modules/react-toolbox/lib/date_picker/theme.scss Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected character '@' (1:0)
    at Parser.pp.raise (/Users/david/projects/pexwidgets/node_modules/webpack/node_modules/acorn/dist/acorn.js:923:13)
    at Parser.pp.getTokenFromCode (/Users/david/projects/pexwidgets/node_modules/webpack/node_modules/acorn/dist/acorn.js:2831:8)
    at Parser.pp.readToken (/Users/david/projects/pexwidgets/node_modules/webpack/node_modules/acorn/dist/acorn.js:2526:15)
    at Parser.pp.nextToken (/Users/david/projects/pexwidgets/node_modules/webpack/node_modules/acorn/dist/acorn.js:2518:71)
    at Parser.parse (/Users/david/projects/pexwidgets/node_modules/webpack/node_modules/acorn/dist/acorn.js:1631:10)
    at Object.parse (/Users/david/projects/pexwidgets/node_modules/webpack/node_modules/acorn/dist/acorn.js:885:44)
    at Parser.parse (/Users/david/projects/pexwidgets/node_modules/webpack/lib/Parser.js:902:15)
    at DependenciesBlock.<anonymous> (/Users/david/projects/pexwidgets/node_modules/webpack/lib/NormalModule.js:104:16)
    at DependenciesBlock.onModuleBuild (/Users/david/projects/pexwidgets/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
    at nextLoader (/Users/david/projects/pexwidgets/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
 @ ./~/react-toolbox/lib/date_picker/index.js 36:13-36

ERROR in ./~/react-toolbox/lib/button/theme.scss
Module parse failed: /Users/david/projects/pexwidgets/node_modules/react-toolbox/lib/button/theme.scss Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected character '@' (1:0)
    at Parser.pp.raise (/Users/david/projects/pexwidgets/node_modules/webpack/node_modules/acorn/dist/acorn.js:923:13)
    at Parser.pp.getTokenFromCode (/Users/david/projects/pexwidgets/node_modules/webpack/node_modules/acorn/dist/acorn.js:2831:8)
    at Parser.pp.readToken (/Users/david/projects/pexwidgets/node_modules/webpack/node_modules/acorn/dist/acorn.js:2526:15)
    at Parser.pp.nextToken (/Users/david/projects/pexwidgets/node_modules/webpack/node_modules/acorn/dist/acorn.js:2518:71)
    at Parser.parse (/Users/david/projects/pexwidgets/node_modules/webpack/node_modules/acorn/dist/acorn.js:1631:10)
    at Object.parse (/Users/david/projects/pexwidgets/node_modules/webpack/node_modules/acorn/dist/acorn.js:885:44)
    at Parser.parse (/Users/david/projects/pexwidgets/node_modules/webpack/lib/Parser.js:902:15)
    at DependenciesBlock.<anonymous> (/Users/david/projects/pexwidgets/node_modules/webpack/lib/NormalModule.js:104:16)
    at DependenciesBlock.onModuleBuild (/Users/david/projects/pexwidgets/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
    at nextLoader (/Users/david/projects/pexwidgets/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
 @ ./~/react-toolbox/lib/button/index.js 24:13-36

ERROR in ./~/react-toolbox/lib/input/theme.scss
Module parse failed: /Users/david/projects/pexwidgets/node_modules/react-toolbox/lib/input/theme.scss Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected character '@' (1:0)
    at Parser.pp.raise (/Users/david/projects/pexwidgets/node_modules/webpack/node_modules/acorn/dist/acorn.js:923:13)
    at Parser.pp.getTokenFromCode (/Users/david/projects/pexwidgets/node_modules/webpack/node_modules/acorn/dist/acorn.js:2831:8)
    at Parser.pp.readToken (/Users/david/projects/pexwidgets/node_modules/webpack/node_modules/acorn/dist/acorn.js:2526:15)
    at Parser.pp.nextToken (/Users/david/projects/pexwidgets/node_modules/webpack/node_modules/acorn/dist/acorn.js:2518:71)
    at Parser.parse (/Users/david/projects/pexwidgets/node_modules/webpack/node_modules/acorn/dist/acorn.js:1631:10)
    at Object.parse (/Users/david/projects/pexwidgets/node_modules/webpack/node_modules/acorn/dist/acorn.js:885:44)
    at Parser.parse (/Users/david/projects/pexwidgets/node_modules/webpack/lib/Parser.js:902:15)
    at DependenciesBlock.<anonymous> (/Users/david/projects/pexwidgets/node_modules/webpack/lib/NormalModule.js:104:16)
    at DependenciesBlock.onModuleBuild (/Users/david/projects/pexwidgets/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
    at nextLoader (/Users/david/projects/pexwidgets/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
 @ ./~/react-toolbox/lib/input/index.js 18:13-36

ERROR in ./~/react-toolbox/lib/dialog/theme.scss
Module parse failed: /Users/david/projects/pexwidgets/node_modules/react-toolbox/lib/dialog/theme.scss Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected character '@' (1:0)
    at Parser.pp.raise (/Users/david/projects/pexwidgets/node_modules/webpack/node_modules/acorn/dist/acorn.js:923:13)
    at Parser.pp.getTokenFromCode (/Users/david/projects/pexwidgets/node_modules/webpack/node_modules/acorn/dist/acorn.js:2831:8)
    at Parser.pp.readToken (/Users/david/projects/pexwidgets/node_modules/webpack/node_modules/acorn/dist/acorn.js:2526:15)
    at Parser.pp.nextToken (/Users/david/projects/pexwidgets/node_modules/webpack/node_modules/acorn/dist/acorn.js:2518:71)
    at Parser.parse (/Users/david/projects/pexwidgets/node_modules/webpack/node_modules/acorn/dist/acorn.js:1631:10)
    at Object.parse (/Users/david/projects/pexwidgets/node_modules/webpack/node_modules/acorn/dist/acorn.js:885:44)
    at Parser.parse (/Users/david/projects/pexwidgets/node_modules/webpack/lib/Parser.js:902:15)
    at DependenciesBlock.<anonymous> (/Users/david/projects/pexwidgets/node_modules/webpack/lib/NormalModule.js:104:16)
    at DependenciesBlock.onModuleBuild (/Users/david/projects/pexwidgets/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
    at nextLoader (/Users/david/projects/pexwidgets/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
 @ ./~/react-toolbox/lib/dialog/index.js 22:13-36

ERROR in ./~/react-toolbox/lib/animations/slide-left.scss
Module parse failed: /Users/david/projects/pexwidgets/node_modules/react-toolbox/lib/animations/slide-left.scss Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (1:0)
    at Parser.pp.raise (/Users/david/projects/pexwidgets/node_modules/webpack/node_modules/acorn/dist/acorn.js:923:13)
    at Parser.pp.unexpected (/Users/david/projects/pexwidgets/node_modules/webpack/node_modules/acorn/dist/acorn.js:1490:8)
    at Parser.pp.parseExprAtom (/Users/david/projects/pexwidgets/node_modules/webpack/node_modules/acorn/dist/acorn.js:333:12)
    at Parser.pp.parseExprSubscripts (/Users/david/projects/pexwidgets/node_modules/webpack/node_modules/acorn/dist/acorn.js:228:19)
    at Parser.pp.parseMaybeUnary (/Users/david/projects/pexwidgets/node_modules/webpack/node_modules/acorn/dist/acorn.js:207:17)
    at Parser.pp.parseExprOps (/Users/david/projects/pexwidgets/node_modules/webpack/node_modules/acorn/dist/acorn.js:154:19)
    at Parser.pp.parseMaybeConditional (/Users/david/projects/pexwidgets/node_modules/webpack/node_modules/acorn/dist/acorn.js:136:19)
    at Parser.pp.parseMaybeAssign (/Users/david/projects/pexwidgets/node_modules/webpack/node_modules/acorn/dist/acorn.js:112:19)
    at Parser.pp.parseExpression (/Users/david/projects/pexwidgets/node_modules/webpack/node_modules/acorn/dist/acorn.js:88:19)
    at Parser.pp.parseStatement (/Users/david/projects/pexwidgets/node_modules/webpack/node_modules/acorn/dist/acorn.js:1771:23)
 @ ./~/react-toolbox/lib/animations/index.js 8:17-45

ERROR in ./~/react-toolbox/lib/animations/slide-right.scss
Module parse failed: /Users/david/projects/pexwidgets/node_modules/react-toolbox/lib/animations/slide-right.scss Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (1:0)
    at Parser.pp.raise (/Users/david/projects/pexwidgets/node_modules/webpack/node_modules/acorn/dist/acorn.js:923:13)
    at Parser.pp.unexpected (/Users/david/projects/pexwidgets/node_modules/webpack/node_modules/acorn/dist/acorn.js:1490:8)
    at Parser.pp.parseExprAtom (/Users/david/projects/pexwidgets/node_modules/webpack/node_modules/acorn/dist/acorn.js:333:12)
    at Parser.pp.parseExprSubscripts (/Users/david/projects/pexwidgets/node_modules/webpack/node_modules/acorn/dist/acorn.js:228:19)
    at Parser.pp.parseMaybeUnary (/Users/david/projects/pexwidgets/node_modules/webpack/node_modules/acorn/dist/acorn.js:207:17)
    at Parser.pp.parseExprOps (/Users/david/projects/pexwidgets/node_modules/webpack/node_modules/acorn/dist/acorn.js:154:19)
    at Parser.pp.parseMaybeConditional (/Users/david/projects/pexwidgets/node_modules/webpack/node_modules/acorn/dist/acorn.js:136:19)
    at Parser.pp.parseMaybeAssign (/Users/david/projects/pexwidgets/node_modules/webpack/node_modules/acorn/dist/acorn.js:112:19)
    at Parser.pp.parseExpression (/Users/david/projects/pexwidgets/node_modules/webpack/node_modules/acorn/dist/acorn.js:88:19)
    at Parser.pp.parseStatement (/Users/david/projects/pexwidgets/node_modules/webpack/node_modules/acorn/dist/acorn.js:1771:23)
 @ ./~/react-toolbox/lib/animations/index.js 12:18-47

ERROR in ./~/react-toolbox/lib/animations/zoom-in.scss
Module parse failed: /Users/david/projects/pexwidgets/node_modules/react-toolbox/lib/animations/zoom-in.scss Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected character '@' (1:0)
    at Parser.pp.raise (/Users/david/projects/pexwidgets/node_modules/webpack/node_modules/acorn/dist/acorn.js:923:13)
    at Parser.pp.getTokenFromCode (/Users/david/projects/pexwidgets/node_modules/webpack/node_modules/acorn/dist/acorn.js:2831:8)
    at Parser.pp.readToken (/Users/david/projects/pexwidgets/node_modules/webpack/node_modules/acorn/dist/acorn.js:2526:15)
    at Parser.pp.nextToken (/Users/david/projects/pexwidgets/node_modules/webpack/node_modules/acorn/dist/acorn.js:2518:71)
    at Parser.parse (/Users/david/projects/pexwidgets/node_modules/webpack/node_modules/acorn/dist/acorn.js:1631:10)
    at Object.parse (/Users/david/projects/pexwidgets/node_modules/webpack/node_modules/acorn/dist/acorn.js:885:44)
    at Parser.parse (/Users/david/projects/pexwidgets/node_modules/webpack/lib/Parser.js:902:15)
    at DependenciesBlock.<anonymous> (/Users/david/projects/pexwidgets/node_modules/webpack/lib/NormalModule.js:104:16)
    at DependenciesBlock.onModuleBuild (/Users/david/projects/pexwidgets/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
    at nextLoader (/Users/david/projects/pexwidgets/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
 @ ./~/react-toolbox/lib/animations/index.js 16:14-39

ERROR in ./~/react-toolbox/lib/animations/zoom-out.scss
Module parse failed: /Users/david/projects/pexwidgets/node_modules/react-toolbox/lib/animations/zoom-out.scss Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected character '@' (1:0)
    at Parser.pp.raise (/Users/david/projects/pexwidgets/node_modules/webpack/node_modules/acorn/dist/acorn.js:923:13)
    at Parser.pp.getTokenFromCode (/Users/david/projects/pexwidgets/node_modules/webpack/node_modules/acorn/dist/acorn.js:2831:8)
    at Parser.pp.readToken (/Users/david/projects/pexwidgets/node_modules/webpack/node_modules/acorn/dist/acorn.js:2526:15)
    at Parser.pp.nextToken (/Users/david/projects/pexwidgets/node_modules/webpack/node_modules/acorn/dist/acorn.js:2518:71)
    at Parser.parse (/Users/david/projects/pexwidgets/node_modules/webpack/node_modules/acorn/dist/acorn.js:1631:10)
    at Object.parse (/Users/david/projects/pexwidgets/node_modules/webpack/node_modules/acorn/dist/acorn.js:885:44)
    at Parser.parse (/Users/david/projects/pexwidgets/node_modules/webpack/lib/Parser.js:902:15)
    at DependenciesBlock.<anonymous> (/Users/david/projects/pexwidgets/node_modules/webpack/lib/NormalModule.js:104:16)
    at DependenciesBlock.onModuleBuild (/Users/david/projects/pexwidgets/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
    at nextLoader (/Users/david/projects/pexwidgets/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
 @ ./~/react-toolbox/lib/animations/index.js 20:15-41

ERROR in ./~/react-toolbox/lib/ripple/theme.scss
Module parse failed: /Users/david/projects/pexwidgets/node_modules/react-toolbox/lib/ripple/theme.scss Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected character '@' (1:0)
    at Parser.pp.raise (/Users/david/projects/pexwidgets/node_modules/webpack/node_modules/acorn/dist/acorn.js:923:13)
    at Parser.pp.getTokenFromCode (/Users/david/projects/pexwidgets/node_modules/webpack/node_modules/acorn/dist/acorn.js:2831:8)
    at Parser.pp.readToken (/Users/david/projects/pexwidgets/node_modules/webpack/node_modules/acorn/dist/acorn.js:2526:15)
    at Parser.pp.nextToken (/Users/david/projects/pexwidgets/node_modules/webpack/node_modules/acorn/dist/acorn.js:2518:71)
    at Parser.parse (/Users/david/projects/pexwidgets/node_modules/webpack/node_modules/acorn/dist/acorn.js:1631:10)
    at Object.parse (/Users/david/projects/pexwidgets/node_modules/webpack/node_modules/acorn/dist/acorn.js:885:44)
    at Parser.parse (/Users/david/projects/pexwidgets/node_modules/webpack/lib/Parser.js:902:15)
    at DependenciesBlock.<anonymous> (/Users/david/projects/pexwidgets/node_modules/webpack/lib/NormalModule.js:104:16)
    at DependenciesBlock.onModuleBuild (/Users/david/projects/pexwidgets/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
    at nextLoader (/Users/david/projects/pexwidgets/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
 @ ./~/react-toolbox/lib/ripple/index.js 13:13-36

ERROR in ./~/react-toolbox/lib/overlay/theme.scss
Module parse failed: /Users/david/projects/pexwidgets/node_modules/react-toolbox/lib/overlay/theme.scss Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected character '@' (1:0)
    at Parser.pp.raise (/Users/david/projects/pexwidgets/node_modules/webpack/node_modules/acorn/dist/acorn.js:923:13)
    at Parser.pp.getTokenFromCode (/Users/david/projects/pexwidgets/node_modules/webpack/node_modules/acorn/dist/acorn.js:2831:8)
    at Parser.pp.readToken (/Users/david/projects/pexwidgets/node_modules/webpack/node_modules/acorn/dist/acorn.js:2526:15)
    at Parser.pp.nextToken (/Users/david/projects/pexwidgets/node_modules/webpack/node_modules/acorn/dist/acorn.js:2518:71)
    at Parser.parse (/Users/david/projects/pexwidgets/node_modules/webpack/node_modules/acorn/dist/acorn.js:1631:10)
    at Object.parse (/Users/david/projects/pexwidgets/node_modules/webpack/node_modules/acorn/dist/acorn.js:885:44)
    at Parser.parse (/Users/david/projects/pexwidgets/node_modules/webpack/lib/Parser.js:902:15)
    at DependenciesBlock.<anonymous> (/Users/david/projects/pexwidgets/node_modules/webpack/lib/NormalModule.js:104:16)
    at DependenciesBlock.onModuleBuild (/Users/david/projects/pexwidgets/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
    at nextLoader (/Users/david/projects/pexwidgets/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
 @ ./~/react-toolbox/lib/overlay/index.js 14:13-36

**Comment by javivelasco** [comment]
Your config is wrong. Your module bundler should able to require scss from node_modules. Check the example repo to see a working example :)
