### ISSUE TITLE
I cant get this to work with webpack

### ISSUE THREAD

**Issue by jasan-s** [react-toolbox/react-toolbox#792]
```
    loaders: [
      {test: /\.js$/, exclude: /node_modules/, loader: 'babel-loader'},
      {test: /\.style.js$/, loader: 'style!css!postcss?parser=postcss-js!babel'},
      {test: /\.(scss|css)$/, loader: 'style!css?sourceMap&modules&localIdentName=[name]__[local]___[hash:base64:5]&importLoader=1!postcss!sass'}
    ]
```

is this config correct?

**Comment by squirmsound** [comment]
Neither can I. I have been trying to figure this out but get an error everytime I import like this.

```
import { Button } from 'react-toolbox/lib/button';
```
This works.

```
import FontIcon from 'react-toolbox/lib/font_icon';
```
I get the error below once I import another component.
```
import FontIcon from 'react-toolbox/lib/font_icon';
import { Button } from 'react-toolbox/lib/button';
```

### ERROR OUTPUT

```
ERROR in ./~/react-toolbox/lib/button/theme.scss
Module build failed: ModuleBuildError: Module build failed:
@import "../colors";
^
      File to import not found or unreadable: theme/_config.scss
Parent style sheet: stdin
      in /Users/squirm/Desktop/engineering/_contract/bounties-frontend/node_modules/react-toolbox/lib/button/theme.scss (line 1, column 1)
    at DependenciesBlock.onModuleBuildFailed (/Users/squirm/Desktop/engineering/_contract/bounties-frontend/node_modules/webpack-core/lib/NormalModuleMixin.js:315:19)
    at nextLoader (/Users/squirm/Desktop/engineering/_contract/bounties-frontend/node_modules/webpack-core/lib/NormalModuleMixin.js:270:31)
    at /Users/squirm/Desktop/engineering/_contract/bounties-frontend/node_modules/webpack-core/lib/NormalModuleMixin.js:292:15
    at context.callback (/Users/squirm/Desktop/engineering/_contract/bounties-frontend/node_modules/webpack-core/lib/NormalModuleMixin.js:148:14)
    at Object.onRender (/Users/squirm/Desktop/engineering/_contract/bounties-frontend/node_modules/sass-loader/index.js:272:13)
    at /Users/squirm/Desktop/engineering/_contract/bounties-frontend/node_modules/sass-loader/node_modules/async/lib/async.js:906:35
    at _arrayEach (/Users/squirm/Desktop/engineering/_contract/bounties-frontend/node_modules/sass-loader/node_modules/async/lib/async.js:85:13)
    at Object.<anonymous> (/Users/squirm/Desktop/engineering/_contract/bounties-frontend/node_modules/sass-loader/node_modules/async/lib/async.js:898:17)
    at Object.callback (/Users/squirm/Desktop/engineering/_contract/bounties-frontend/node_modules/sass-loader/node_modules/async/lib/async.js:44:16)
    at options.error (/Users/squirm/Desktop/engineering/_contract/bounties-frontend/node_modules/node-sass/lib/index.js:295:32)
 @ ./~/react-toolbox/lib/button/index.js 24:13-36

ERROR in ./~/react-toolbox/lib/ripple/theme.scss
Module build failed: ModuleBuildError: Module build failed:
@import "../colors";
^
      File to import not found or unreadable: theme/_config.scss
Parent style sheet: stdin
      in /Users/squirm/Desktop/engineering/_contract/bounties-frontend/node_modules/react-toolbox/lib/ripple/theme.scss (line 1, column 1)
    at DependenciesBlock.onModuleBuildFailed (/Users/squirm/Desktop/engineering/_contract/bounties-frontend/node_modules/webpack-core/lib/NormalModuleMixin.js:315:19)
    at nextLoader (/Users/squirm/Desktop/engineering/_contract/bounties-frontend/node_modules/webpack-core/lib/NormalModuleMixin.js:270:31)
    at /Users/squirm/Desktop/engineering/_contract/bounties-frontend/node_modules/webpack-core/lib/NormalModuleMixin.js:292:15
    at context.callback (/Users/squirm/Desktop/engineering/_contract/bounties-frontend/node_modules/webpack-core/lib/NormalModuleMixin.js:148:14)
    at Object.onRender (/Users/squirm/Desktop/engineering/_contract/bounties-frontend/node_modules/sass-loader/index.js:272:13)
    at /Users/squirm/Desktop/engineering/_contract/bounties-frontend/node_modules/sass-loader/node_modules/async/lib/async.js:906:35
    at _arrayEach (/Users/squirm/Desktop/engineering/_contract/bounties-frontend/node_modules/sass-loader/node_modules/async/lib/async.js:85:13)
    at Object.<anonymous> (/Users/squirm/Desktop/engineering/_contract/bounties-frontend/node_modules/sass-loader/node_modules/async/lib/async.js:898:17)
    at Object.callback (/Users/squirm/Desktop/engineering/_contract/bounties-frontend/node_modules/sass-loader/node_modules/async/lib/async.js:44:16)
    at options.error (/Users/squirm/Desktop/engineering/_contract/bounties-frontend/node_modules/node-sass/lib/index.js:295:32)
 @ ./~/react-toolbox/lib/ripple/index.js 13:13-36
Child html-webpack-plugin for "index.html":
         Asset    Size  Chunks       Chunk Names
    index.html  548 kB       0
    chunk    {0} index.html 528 kB [rendered]
        [0] ./~/html-webpack-plugin/lib/loader.js!./~/html-webpack-plugin/default_index.ejs 550 bytes {0} [built]
        [1] ./~/html-webpack-plugin/~/lodash/lodash.js 527 kB {0} [built]
        [2] (webpack)/buildin/module.js 251 bytes {0} [built]
Child extract-text-webpack-plugin:

    ERROR in ./~/css-loader!./~/sass-loader!./~/toolbox-loader!./~/react-toolbox/lib/button/theme.scss
    Module build failed:
    @import "../colors";
    ^
          File to import not found or unreadable: theme/_config.scss
    Parent style sheet: stdin
          in /Users/squirm/Desktop/engineering/_contract/bounties-frontend/node_modules/react-toolbox/lib/button/theme.scss (line 1, column 1)
Child extract-text-webpack-plugin:

    ERROR in ./~/css-loader!./~/sass-loader!./~/toolbox-loader!./~/react-toolbox/lib/ripple/theme.scss
    Module build failed:
    @import "../colors";
    ^
          File to import not found or unreadable: theme/_config.scss
    Parent style sheet: stdin
          in /Users/squirm/Desktop/engineering/_contract/bounties-frontend/node_modules/react-toolbox/lib/ripple/theme.scss (line 1, column 1)
```
### js file

```
import React, { Component } from 'react';
import { toMoney, toDateTime, toTitleCase } from '../../../util/formatters';
import { Row, Col } from 'react-bootstrap';
import classNames from 'classnames';
import momentT from 'moment-timezone';
import styles from './card-type-a.less';
import FontIcon from 'react-toolbox/lib/font_icon';
import { Button } from 'react-toolbox/lib/button';

class Card extends Component {
  componentDidMount() {
    styles.use();
  }

  componentWillUnmount() {
    styles.unuse();
  }
  render() {
    const { things } = this.props;

    const creatorClasses = classNames({
      // 'p-h-md': true,
      'p-t-sm': true,
      // 'text-center': false,
      'no-margin': true,
    });

    const failCondClasses = classNames({
      // 'p-h-md': true,
      'p-t-sm': true,
      // 'text-center': false,
      'no-margin': true,
    });

    const challengeClasses = classNames({
      // 'p-h-md': true,
      'p-t-sm': true,
      // 'text-center': false,
      'no-margin': true,
    });

    const controlsClasses = classNames({
      controls: true,
      'p-b-n': true,
      'p-t-md': true,
      'no-margin': true,
    });
    const rowImgClasses = classNames({
      'p-xs': true,
      'text-center': false,
      'no-margin': true,
    });
    const created = momentT(things.created_at);
    const date = created.tz('America/Los_Angeles').format('LL');

    return (
      <div className="things card p-md" key={things.id}>
        <Row className={`${creatorClasses}`}>
          <Col sm={8} className={`creator no-padding`}>
            <span className={`date`}>
              {date}
            </span>
            <h5 className={`user`}>
              {things.initiator_name}
            </h5>
          </Col>
          <Col sm={4}>
            <Row className={`amount`}>
              <h2 className="value">
                $ {things.total_amount}
              </h2>
            </Row>
          </Col>
        </Row>

        <Row className={`challenge ${challengeClasses}`}>
          <FontIcon value='location_searching' />
          <h2>{things.challenge}</h2>
        </Row>

        <Row className={`failcondition p-b-md ${failCondClasses}`}>
          <FontIcon value='new_releases' />
          <p>{things.fail_condition}</p>
        </Row>

        <Row className={`${controlsClasses}`}>
          <div className="pull-left social">
            <FontIcon value='thumb_up' />
            {things.up_votes_count}
            <FontIcon value='thumb_down' />
            {things.down_votes_count}

          </div>
          <div className="pull-right">
            <FontIcon value='tag_faces' />
            <FontIcon value='publish' />
            <FontIcon value='verified_user' />
            <FontIcon value='do_not_disturb_alt' />
            <Button icon='add' floating />
          </div>
        </Row>
      </div>
    );
  }
}

export default Card;

```


##WEBPACK CONFIG
```
const webpack           = require('webpack');
const R                 = require('ramda');
const React             = require('react');
const nutil             = require('util');
const glob              = require('glob');
const fmt               = nutil.format;
const HtmlWebpackPlugin = require('html-webpack-plugin');
const ExtractTextPlugin = require('extract-text-webpack-plugin');
const path              = require('path');

const ENV               = process.env;
const PROJECT_DIR       = ENV.PROJECT_DIR
const ENTRY_DIR         = path.join(PROJECT_DIR, 'src', 'entry');
const DIST_DIR          = path.join(PROJECT_DIR, 'dist');
const PACKAGE_INFO      = require(path.join(PROJECT_DIR, 'package'));
const VERSION_DIR       = path.join(DIST_DIR, PACKAGE_INFO.version);
const OUTPUT_DIR        = path.join(VERSION_DIR, 'pub');
const DEVELOPMENT       = 'development';
const PRODUCTION        = 'production';
const TESTING           = 'test';
const autoprefixer = require('autoprefixer');
const postcssImport = require('postcss-import');
const postcssUrl = require('postcss-url');

const NODE_ENV = ENV.NODE_ENV;
if (!NODE_ENV) {
  // if we're running as a dev server we always are in development mode
  NODE_ENV = process.argv[1].match(/webpack-dev-server$/) ?
  DEVELOPMENT :
  PRODUCTION;
}

const DEV  = NODE_ENV === DEVELOPMENT;
const TEST = NODE_ENV === TESTING;
const PROD = NODE_ENV === PRODUCTION;

const PROTOCOL = ENV.PROTOCOL || 'http';
const HOSTNAME = ENV.HOSTNAME || 'localhost';
const PORT     = parseInt(ENV.PORT || 8084, 10);
const HOST     = PROD ? '/' : fmt('%s://%s:%s/', PROTOCOL, HOSTNAME, PORT);

const JS_BUNDLE_NAME  = PROD ? '[name].[hash].js'  : '[name].bundle.js';
const CSS_BUNDLE_NAME = PROD ? '[name].[hash].css' : '[name].bundle.css';

module.exports = {
  debug:     !PROD,
  bail:      PROD,
  colors:    true,
  progress:  true,
  //--------------------------------------------------------------------------
  // Entry Points and Output
  //--------------------------------------------------------------------------
  // entry: TEST ? {} : { 'app': './src/app.js' },
  entry: TEST ? {} :
  glob.sync(ENTRY_DIR + '/*.js')
  .map(function(filepath) {
    const ext = path.extname(filepath);
    const base = path.basename(filepath, ext);
    const o = {};
    o[base] = filepath;
    return o;
  }).
  reduce(R.merge, {
    vendors: [
      'webpack-material-design-icons',
    ],
  }),

  output: TEST ? {} : {
    path:          OUTPUT_DIR,
    filename:      JS_BUNDLE_NAME,
    publicPath:    HOST,
    chunkFilename: JS_BUNDLE_NAME
  },
  devtool: TEST ? 'eval' : PROD ? 'source-map' : 'eval',
  resolve: {
    extensions: ['', '.js', '.jsx', '.less', '.css', '.scss'],
    modulesDirectories: [
      'node_modules',
      path.resolve(__dirname, './node_modules')
    ]
  },
  //--------------------------------------------------------------------------
  // Loaders
  //--------------------------------------------------------------------------
  module: {
    preLoaders: [
      { test: /\.svg$/, loader: 'svgo?useConfig=svgoConfig' }
    ],

    get loaders() {
      const loaders = [
        { test: /\.json$/, loaders: ['json-loader'] },
        {
          test: /\.js$/,
          exclude: /node_modules/,
          loader: 'babel',
          query: { presets: ['es2015', 'react', 'stage-1'] }
        },
        {
          test: /\.css$/,
          loaders: ['style', 'css'],
          exclude: /(node_modules)\/react-toolbox/
        },
        {
          test: /(\.scss|\.css)$/,
          include : /(node_modules)\/react-toolbox/,
          loader: ExtractTextPlugin.extract('style', 'css!sass!toolbox'),
        },
        { test: /\.less/, loader: 'style/useable!css!less' },
        {
          test: /\.woff$/,
          loader: 'url-loader?limit=10000&mimetype=application/font-woff&name=[path][name].[ext]'
        },
        {
          test: /\.woff2$/,
          loader: 'url-loader?limit=10000&mimetype=application/font-woff2&name=[path][name].[ext]',
        },
        {
          test: /\.svg$/,
          loader: 'url-loader?limit=10000&mimetype=image/svg+xml&name=[path][name].[ext]',
        },
        { test: /\.(jpe?g|png|gif|eot|ttf|svg|woff(2)?)(\?v=\d+\.\d+\.\d+)?/, loader: 'url-loader?limit=100000'
        },
      ];

      if (TEST) {
        loaders.push({
          test: /\.css$/,
          loader: ExtractTextPlugin.extract('style', 'css?sourceMap')
        });
      }
      return loaders;
    }
  },
  toolbox: {theme: './src/theme/theme.scss'},
  postcss: function() {
    return [
      postcssImport({ addDependencyTo: webpack }),
      postcssUrl(),
      autoprefixer,
    ];
  },
  sassLoader: {
    data: '@import "theme/_config.scss";',
    includePaths: [path.resolve(__dirname, './src/static')]
  },
  //--------------------------------------------------------------------------
  // Plugins
  //--------------------------------------------------------------------------
  get plugins() {
    const plugins = [
      new ExtractTextPlugin('bundle.css', { allChunks: true }),
      new webpack.DefinePlugin({
        'process.env.NODE_ENV': JSON.stringify(NODE_ENV)
      }),
      new webpack.ProvidePlugin({
        $: 'jquery',
        jQuery: 'jquery',
      }),
    ];

    if (DEV || PROD) {
      plugins.push(
        new HtmlWebpackPlugin({
          title: 'squirmlabs',
          minify: PROD ? {} : false,
          filename: 'index.html'
        })
      );
    }

    if (PROD) {
      plugins.push(
        new ExtractTextPlugin(CSS_BUNDLE_NAME, { allChunks: false }),
        new webpack.NoErrorsPlugin(),
        new webpack.optimize.DedupePlugin(),
        new webpack.optimize.UglifyJsPlugin()
      );
    }

    return plugins;
  },


  //--------------------------------------------------------------------------
  // Dev Server Configuration
  //--------------------------------------------------------------------------
  devServer: {
    host: HOSTNAME,
    port: PORT,
    https: (/^https$/).test(PROTOCOL),
    contentBase: OUTPUT_DIR,
    hot: false,
    inline: true,
    stats: {
      modules: false,
      cached: false,
      colors: true,
      chunk: false
    }
  }
};
```



## FOLDER STRUCTURE
```
+-- lib
|   +-- config
|   |   +-- server.js
|   |   +-- webpack.config.js
|   |   +-- webpack.test.js
+-- src
|   +-- actions
|   +-- component
|   +-- containers
|   +-- entry
|   +-- img
|   +-- reducers
|   +-- routes
|   +-- static
|   |   +-- theme
|   |   |   +-- theme.js
|   |   |   +-- theme.scss
+-- util
```

## DESIRED STRUCTURE
```
+-- lib
|   +-- config
|   |   +-- server.js
|   |   +-- webpack.config.js
|   |   +-- webpack.test.js
+-- src
|   +-- actions
|   +-- component
|   +-- containers
|   +-- entry
|   +-- reducers
|   +-- routes
+-- static
|   +-- img
|   +-- theme
|   |   +-- theme.js
|   |   +-- theme.scss
+-- util

```

### theme.js
```
import 'react-toolbox/commons';

import ToolboxAppBar from 'react-toolbox/app_bar/theme.scss';
import ToolboxAutocomplete from 'react-toolbox/autocomplete/theme.scss';
import ToolboxAvatar from 'react-toolbox/avatar/theme.scss';
import ToolboxButton from 'react-toolbox/button/theme.scss';
import ToolboxCard from 'react-toolbox/card/theme.scss';
import ToolboxCheckbox from 'react-toolbox/checkbox/theme.scss';
import ToolboxChip from 'react-toolbox/chip/theme.scss';
import ToolboxDatePicker from 'react-toolbox/date_picker/theme.scss';
import ToolboxDialog from 'react-toolbox/dialog/theme.scss';
import ToolboxDrawer from 'react-toolbox/drawer/theme.scss';
import ToolboxDropdown from 'react-toolbox/dropdown/theme.scss';
import ToolboxInput from 'react-toolbox/input/theme.scss';
import ToolboxLayout from 'react-toolbox/layout/theme.scss';
import ToolboxLink from 'react-toolbox/link/theme.scss';
import ToolboxList from 'react-toolbox/list/theme.scss';
import ToolboxMenu from 'react-toolbox/menu/theme.scss';
import ToolboxNavigation from 'react-toolbox/navigation/theme.scss';
import ToolboxOverlay from 'react-toolbox/overlay/theme.scss';
import ToolboxProgress from 'react-toolbox/progress_bar/theme.scss';
import ToolboxRadio from 'react-toolbox/radio/theme.scss';
import ToolboxRipple from 'react-toolbox/ripple/theme.scss';
import ToolboxSlider from 'react-toolbox/slider/theme.scss';
import ToolboxSnackbar from 'react-toolbox/snackbar/theme.scss';
import ToolboxSwitch from 'react-toolbox/switch/theme.scss';
import ToolboxTable from 'react-toolbox/table/theme.scss';
import ToolboxTabs from 'react-toolbox/tabs/theme.scss';
import ToolboxTimePicker from 'react-toolbox/time_picker/theme.scss';
import ToolboxTooltip from 'react-toolbox/tooltip/theme.scss';

export default {
  ToolboxAppBar,
  ToolboxAutocomplete,
  ToolboxAvatar,
  ToolboxButton,
  ToolboxCard,
  ToolboxCheckbox,
  ToolboxChip,
  ToolboxDatePicker,
  ToolboxDialog,
  ToolboxDrawer,
  ToolboxDropdown,
  ToolboxInput,
  ToolboxLayout,
  ToolboxLink,
  ToolboxList,
  ToolboxMenu,
  ToolboxNavigation,
  ToolboxOverlay,
  ToolboxProgress,
  ToolboxRadio,
  ToolboxRipple,
  ToolboxSlider,
  ToolboxSnackbar,
  ToolboxSwitch,
  ToolboxTable,
  ToolboxTabs,
  ToolboxTimePicker,
  ToolboxTooltip
};
```

###theme.scss
```
@import "~react-toolbox/colors"; // Import minimal colors

$color-primary: $palette-indigo-500;
$color-primary-dark: $palette-indigo-700;
$color-primary-light: $palette-indigo-500;
$color-accent: $palette-pink-a200;
$color-accent-dark: $palette-pink-700;
$color-primary-contrast: $color-dark-contrast;
$color-accent-contrast: $color-dark-contrast;
```

**Comment by jasan-s** [comment]
I think i'll wait for version 2.0. So i can use it with css modules instead of needing sass loader

**Comment by coljung** [comment]
I had webpack issues as well, and initially thought it had to do with the configs.

I fixed my issues by:

Adding a reference to my resulting CSS file on my index.html:
```
<link rel="stylesheet" href="styles.css">
```

On webpackconfig i added this line:
```javascript
new ExtractTextPlugin('styles.css', { allChunks: true }),
```

And on my main app entry point i added:
```javascript
import 'react-toolbox/lib/commons.scss';
```

I think the first 2 are the main ones, and i found this wasnt very clear either on the website or here.

**Comment by javivelasco** [comment]
You can use the PostCSS version now if it feels easier but beware the configuration issues would probably be the same because although we no longer compile styles with SASS you still need to enable CSS Modules and it's mostly the same stack.

As @acornejo said, try to start from the example repository, it has a working configuration that would work for most cases just tweaking a bit loaders to your needs
